using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace AccountingSystems.Helpers
{
    public static class CountryCode
    {
        public enum CodeEnum
        {
            [Display(Name = "Afghanistan AF +93")]
            AF = 93,
            [Display(Name = "Åland AX  +358")]
            AX = 358,
            [Display(Name = "Albania AL  +355")]
            AL = 355,
            [Display(Name = "Algeria DZ +213")]
            DZ = 213,
            [Display(Name = "American Samoa AS +684")]
            AS = 684,
            [Display(Name = "Andorra AD +376")]
            AD = 376,
            [Display(Name = "Angola AO +244")]
            AO = 244,
            [Display(Name = "Anguilla AI +264")]
            AI = 264,
            [Display(Name = "Antarctica AQ +672")]
            AQ = 672,
            [Display(Name = "Antigua and Barbuda AG +268")]
            AG = 268,
            [Display(Name = "Argentina AR +54")]
            AR = 54,
            [Display(Name = "Armenia AM +374")]
            AM = 374,
            [Display(Name = "Aruba AW +297")]
            AW = 297,
            [Display(Name = "Australia AU +61")]
            AU = 61,
            [Display(Name = "Austria AT +43")]
            AT = 43,
            [Display(Name = "Azerbaijan AZ +994")]
            AZ = 994,
            [Display(Name = "Bahamas BS +242")]
            BS = 242,
            [Display(Name = "Bahrain BH +973")]
            BH = 973,
            [Display(Name = "Bangladesh BD +880")]
            BD = 880,
            [Display(Name = "Barbados BB +246")]
            BB = 246,
            [Display(Name = "Belarus BY +375")]
            BY = 375,
            [Display(Name = "Belgium BE +32")]
            BE = 32,
            [Display(Name = "Belize BZ +501")]
            BZ = 501,
            [Display(Name = "Benin BJ +229")]
            BJ = 229,
            [Display(Name = "Bermuda BM +441")]
            Bermuda = 441,
            [Display(Name = "Bhutan BT +975")]
            BM = 975,
            [Display(Name = "Bolivia BO +591")]
            BO = 591,
            [Display(Name = "Bosnia and Herzegovina BA  +387")]
            BA = 387,
            [Display(Name = "Botswana BW +267")]
            BW = 267,
            [Display(Name = "Bouvet Island BV +47")]
            BV = 47,
            [Display(Name = "Brazil BR +55")]
            BR = 55,
            [Display(Name = "British Indian Ocean Territory IO +246")]
            IO = 246,
            [Display(Name = "Brunei Darussalam BN +673")]
            BN = 673,
            [Display(Name = "Bulgaria BG +359")]
            BG = 359,
            [Display(Name = "Burkina Faso BF  +226")]
            BF = 226,
            [Display(Name = "Burundi BI +257")]
            Burundi = 257,
            [Display(Name = "Cambodia KH +855")]
            BI = 855,
            [Display(Name = "Cameroon CM +237")]
            CM = 237,
            [Display(Name = "Canada CA +1")]
            CA = 1,
            [Display(Name = "Cape Verde CV +238")]
            CV = 238,
            [Display(Name = "Cayman Islands KY +345")]
            KY = 345,
            [Display(Name = "Central African Republic CF +236")]
            CF = 236,
            [Display(Name = "Chad TD +235")]
            TD = 235,
            [Display(Name = "Chile CL +56")]
            CL = 56,
            [Display(Name = "China CN +86")]
            CN = 86,
            [Display(Name = "Christmas Island CX +61")]
            CX = 61,
            [Display(Name = "Cocos (Keeling) Islands CC +61")]
            CC = 61,
            [Display(Name = "Colombia CO +57")]
            CO = 57,
            [Display(Name = "Comoros KM +269")]
            KM = 269,
            [Display(Name = "Congo (Brazzaville) CG +242")]
            CG = 242,
            [Display(Name = "Congo (Kinshasa) CD +243")]
            CD = 243,
            [Display(Name = "Cook Islands CK +682")]
            CK = 682,
            [Display(Name = "Costa Rica CR +506")]
            CR = 506,
            [Display(Name = "Côte d'Ivoire CI +225")]
            CI = 225,
            [Display(Name = "Croatia HR +385")]
            HR = 385,
            [Display(Name = "Cuba CU +53")]
            CU = 53,
            [Display(Name = "Cyprus CY +357")]
            CY = 357,
            [Display(Name = "Czech Republic CZ +420")]
            CZ = 420,
            [Display(Name = "Denmark DK +45")]
            DK = 45,
            [Display(Name = "Djibouti DJ  +253")]
            DJ = 253,
            [Display(Name = "Dominica DM +767")]
            DM = 767,
            [Display(Name = "Dominican Republic DO +809")]
            DO = 809,
            [Display(Name = "Ecuador EC +593")]
            EC = 593,
            [Display(Name = "Egypt EG +20")]
            EG = 20,
            [Display(Name = "El Salvador SV +503")]
            SV = 503,
            [Display(Name = "Equatorial Guinea GQ +240")]
            GQ = 240,
            [Display(Name = "Eritrea ER +291")]
            ER = 291,
            [Display(Name = "Estonia EE +372")]
            EE = 372,
            [Display(Name = "Ethiopia ET +251")]
            ET = 251,
            [Display(Name = "Falkland Islands FK +500")]
            FK = 500,
            [Display(Name = "Faroe Islands FO +298")]
            FO = 298,
            [Display(Name = "Fiji FJ +679")]
            FJ = 679,
            [Display(Name = "Finland FI +358")]
            FI = 358,
            [Display(Name = "France FR +33")]
            FR = 33,
            [Display(Name = "French Guiana GF +594")]
            GF = 594,
            [Display(Name = "French Polynesia PF +689")]
            PF = 689,
            [Display(Name = "French Southern Lands TF +262")]
            TF = 262,
            [Display(Name = "Gabon GA +241")]
            GA = 241,
            [Display(Name = "Gambia GM +220")]
            GM = 220,
            [Display(Name = "Georgia GE +995")]
            GE = 995,
            [Display(Name = "Germany DE +49")]
            DE = 49,
            [Display(Name = "Ghana GH +233")]
            GH = 233,
            [Display(Name = "Gibraltar GI  +350")]
            GI = 350,
            [Display(Name = "Greece GR +30")]
            GR = 30,
            [Display(Name = "Greenland GL +299")]
            GL = 299,
            [Display(Name = "Grenada GD +473")]
            GD = 473,
            [Display(Name = "Guadeloupe GP +590")]
            GP = 590,
            [Display(Name = "Guam GU +671")]
            GU = 671,
            [Display(Name = "Guatemala GT +502")]
            GT = 502,
            [Display(Name = "Guinea GN +224")]
            GN = 224,
            [Display(Name = "Guinea-Bissau GW +245")]
            GW = 245,
            [Display(Name = "Guyana GY +592")]
            GY = 592,
            [Display(Name = "Haiti HT +509")]
            HT = 509,
            [Display(Name = "Heard and McDonald Islands HM +61")]
            HM = 61,
            [Display(Name = "Honduras HN +504")]
            HN = 504,
            [Display(Name = "Hungary HU +36")]
            HU = 36,
            [Display(Name = "Iceland IS +354")]
            IS = 354,
            [Display(Name = "India IN +91")]
            IN = 91,
            [Display(Name = "Indonesia ID +62")]
            ID = 62,
            [Display(Name = "Iran IR +98")]
            IR = 98,
            [Display(Name = "Iraq IQ +964")]
            IQ = 964,
            [Display(Name = "Ireland IE +353")]
            IE = 353,
            [Display(Name = "Israel IL +972")]
            Israel = 972,
            [Display(Name = "Italy IT +39")]
            IL = 39,
            [Display(Name = "Jamaica JM +876")]
            JM = 876,
            [Display(Name = "Japan JP +81")]
            JP = 81,
            [Display(Name = "Jordan JO +962")]
            JO = 962,
            [Display(Name = "Kazakhstan KZ  +7")]
            KZ = 7,
            [Display(Name = "Kenya KE +254")]
            KE = 254,
            [Display(Name = "Kiribati KI +686")]
            KI = 686,
            [Display(Name = "Kuwait KW +965")]
            KW = 965,
            [Display(Name = "Kyrgyzstan KG +996")]
            KG = 996,
            [Display(Name = "Laos LA +856")]
            LA = 856,
            [Display(Name = "Latvia LV +371")]
            LV = 371,
            [Display(Name = "Lebanon LB +961")]
            LB = 961,
            [Display(Name = "Lesotho LS +266")]
            LS = 266,
            [Display(Name = "Liberia LR +231")]
            LR = 231,
            [Display(Name = "Libya LY +218")]
            LY = 218,
            [Display(Name = "Liechtenstein LI +423")]
            LI = 423,
            [Display(Name = "Lithuania LT +370")]
            LT = 370,
            [Display(Name = "Luxembourg LU +352")]
            LU = 352,
            [Display(Name = "Macedonia MK +389")]
            MK = 389,
            [Display(Name = "Madagascar MG +261")]
            MG = 261,
            [Display(Name = "Malawi MW +265")]
            MW = 265,
            [Display(Name = "Malaysia MY +60")]
            MY = 60,
            [Display(Name = "Maldives MV +960")]
            MV = 960,
            [Display(Name = "Mali ML +223")]
            ML = 223,
            [Display(Name = "Malta MT +356")]
            MT = 356,
            [Display(Name = "Marshall Islands MH +692")]
            MH = 692,
            [Display(Name = "Martinique MQ +596")]
            MQ = 596,
            [Display(Name = "Mauritania MR +222")]
            MR = 222,
            [Display(Name = "Mauritius MU +230")]
            MU = 230,
            [Display(Name = "Mayotte YT +262")]
            YT = 262,
            [Display(Name = "Mexico MX +52")]
            MX = 52,
            [Display(Name = "Micronesia FM +691")]
            FM = 691,
            [Display(Name = "Moldova MD +373")]
            MD = 373,
            [Display(Name = "Monaco MC +377")]
            MC = 377,
            [Display(Name = "Mongolia MN +976")]
            MN = 976,
            [Display(Name = "Montenegro ME +382")]
            ME = 382,
            [Display(Name = "Montserrat MS +664")]
            MS = 664,
            [Display(Name = "Morocco MA +212")]
            MA = 212,
            [Display(Name = "Mozambique MZ +258")]
            MZ = 258,
            [Display(Name = "Myanmar MM +95")]
            MM = 95,
            [Display(Name = "Namibia NA +264")]
            NA = 264,
            [Display(Name = "Nauru NR +674")]
            NR = 674,
            [Display(Name = "Nepal NP +977")]
            NP = 977,
            [Display(Name = "Netherlands Antilles NL +599")]
            NAL = 599,
            [Display(Name = "Netherlands NL +31")]
            NL = 31,
            [Display(Name = "New Caledonia NC +687")]
            NC = 687,
            [Display(Name = "New Zealand NZ +64")]
            NZ = 64,
            [Display(Name = "Nicaragua NI +505")]
            NI = 505,
            [Display(Name = "Niger NE +227")]
            NE = 227,
            [Display(Name = "Nigeria NG +234")]
            NG = 234,
            [Display(Name = "Niue NU +683")]
            NU = 683,
            [Display(Name = "Norfolk Island NF +672")]
            NF = 672,
            [Display(Name = "North Korea KP +850")]
            KP = 850,
            [Display(Name = "Northern Mariana Islands MP +670")]
            MP = 670,
            [Display(Name = "Norway NO +47")]
            NO = 47,
            [Display(Name = "Oman OM +968")]
            OM = 968,
            [Display(Name = "Pakistan PK +92")]
            PK = 92,
            [Display(Name = "Palau PW +680")]
            PW = 680,
            [Display(Name = "Palestine PS +970")]
            PS = 970,
            [Display(Name = "Panama PA +507")]
            PA = 507,
            [Display(Name = "Papua New Guinea PG +675")]
            PG = 675,
            [Display(Name = "Paraguay PY +595")]
            PY = 595,
            [Display(Name = "Peru PE +51")]
            PE = 51,
            [Display(Name = "Philippines PH +63")]
            PH = 63,
            [Display(Name = "Pitcairn Islands PN +64")]
            PN = 64,
            [Display(Name = "Poland PL +48")]
            PL = 48,
            [Display(Name = "Portugal PT +351")]
            PT = 351,
            [Display(Name = "Puerto Rico PR +787")]
            PR1 = 787,
            [Display(Name = "Puerto Rico PR +939")]
            PR2 = 939,
            [Display(Name = "Qatar QA +974")]
            QA = 974,
            [Display(Name = "Reunion RE +262")]
            RE = 262,
            [Display(Name = "Romania RO +40")]
            RO = 40,
            [Display(Name = "Russian Federation RU +7")]
            RU = 7,
            [Display(Name = "Rwanda RW +250")]
            RW = 250,
            [Display(Name = "Saint Helena SH +290")]
            SH = 290,
            [Display(Name = "Saint Kitts and Nevis KN +869")]
            KN = 869,
            [Display(Name = "Saint Lucia LC +758")]
            LC = 758,
            [Display(Name = "Saint Pierre and Miquelon PM +508")]
            PM = 508,
            [Display(Name = "Saint Vincent and the Grenadines VC +784")]
            VC = 784,
            [Display(Name = "Samoa WS +685")]
            WS = 685,
            [Display(Name = "San Marino SM +378")]
            SM = 378,
            [Display(Name = "Sao Tome and Principe ST +239")]
            ST = 239,
            [Display(Name = "Saudi Arabia SA +966")]
            SA = 966,
            [Display(Name = "Senegal SN +221")]
            SN = 221,
            [Display(Name = "Serbia RS +381")]
            RS = 381,
            [Display(Name = "Seychelles SC +248")]
            SC = 248,
            [Display(Name = "Sierra Leone SL +232")]
            SL = 232,
            [Display(Name = "Singapore SG +65")]
            SG = 65,
            [Display(Name = "Slovakia SK +421")]
            SK = 421,
            [Display(Name = "Slovenia SI +386")]
            SI = 386,
            [Display(Name = "Solomon Islands SB +677")]
            SB = 677,
            [Display(Name = "Somalia SO +252")]
            SO = 252,
            [Display(Name = "South Africa ZA +27")]
            ZA = 27,
            [Display(Name = "South Georgia and South Sandwich Islands GS +500")]
            GS = 500,
            [Display(Name = "South Korea KR +82")]
            KR = 82,
            [Display(Name = "Spain ES +34")]
            ES = 34,
            [Display(Name = "Sri Lanka LK +94")]
            LK = 94,
            [Display(Name = "Sudan SD +249")]
            SD = 249,
            [Display(Name = "Suriname SR +597")]
            SR = 597,
            [Display(Name = "Svalbard and Jan Mayen Islands SJ +47")]
            SJ = 47,
            [Display(Name = "Swaziland SZ +268")]
            SZ = 268,
            [Display(Name = "Sweden SE +46")]
            SE = 46,
            [Display(Name = "Switzerland CH +41")]
            CH = 41,
            [Display(Name = "Syria SY +963")]
            SY = 963,
            [Display(Name = "Taiwan TW +886")]
            TW = 886,
            [Display(Name = "Tajikistan TJ +992")]
            TJ = 992,
            [Display(Name = "Tanzania TZ +255")]
            TZ = 255,
            [Display(Name = "Thailand TH +66")]
            TH = 66,
            [Display(Name = "Timor-Leste TL +670")]
            TL = 670,
            [Display(Name = "Togo TG +228")]
            TG = 228,
            [Display(Name = "Tokelau TK +690")]
            TK = 690,
            [Display(Name = "Tonga TO +676")]
            TO = 676,
            [Display(Name = "Trinidad and Tobago TT +868")]
            TT = 868,
            [Display(Name = "Tunisia TN +216")]
            TN = 216,
            [Display(Name = "Turkey TR +90")]
            TR = 90,
            [Display(Name = "Turkmenistan TM +993")]
            TM = 993,
            [Display(Name = "Turks and Caicos Islands TC +649")]
            TC = 649,
            [Display(Name = "Tuvalu TV +688")]
            TV = 688,
            [Display(Name = "Uganda UG +256")]
            UG = 256,
            [Display(Name = "Ukraine UA +380")]
            UA = 380,
            [Display(Name = "United Arab Emirates AE +971")]
            AE = 971,
            [Display(Name = "United Kingdom UK +44")]
            UK = 44,
            [Display(Name = "Uruguay UY +598")]
            UY = 598,
            [Display(Name = "US Minor Outlying Islands UM +699")]
            UM = 699,
            [Display(Name = "USA US +1")]
            US = 1,
            [Display(Name = "Uzbekistan UZ +998")]
            UZ = 998,
            [Display(Name = "Vanuatu VU +678")]
            VU = 678,
            [Display(Name = "Vatican City VA +379")]
            VA = 379,
            [Display(Name = "Venezuela VE  +58")]
            VE = 58,
            [Display(Name = "Vietnam VN  +84")]
            VN = 84,
            [Display(Name = "Virgin Islands (British) VG +284")]
            VG = 284,
            [Display(Name = "Virgin Islands (U.S.) VI +340")]
            VI = 340,
            [Display(Name = "Wallis and Futuna Islands WF +681")]
            WF = 681,
            [Display(Name = "Western Sahara EH +212")]
            EH = 212,
            [Display(Name = "Yemen YE +967")]
            YE = 967,
            [Display(Name = "Zambia ZM +260")]
            ZM = 260,
            [Display(Name = "Zimbabwe ZW +263")]
            ZW = 263
        };

        public enum DescriptionEnum
        {
            //[Display(Name = "Afghanistan")]
            //AF = 93,
            //[Display(Name = "Åland")]
            //AX = 358,
            //[Display(Name = "Albania")]
            //AL = 355,
            //[Display(Name = "Algeria")]
            //DZ = 213,
            //[Display(Name = "American Samoa")]
            //AS = 684,
            //[Display(Name = "Andorra")]
            //AD = 376,
            //[Display(Name = "Angola")]
            //AO = 244,
            //[Display(Name = "Anguilla")]
            //AI = 264,
            //[Display(Name = "Antarctica")]
            //AQ = 672,
            //[Display(Name = "Antigua and Barbuda")]
            //AG = 268,
            //[Display(Name = "Argentina")]
            //AR = 54,
            //[Display(Name = "Armenia")]
            //AM = 374,
            //[Display(Name = "Aruba")]
            //AW = 297,
            //[Display(Name = "Australia")]
            //AU = 61,
            //[Display(Name = "Austria")]
            //AT = 43,
            //[Display(Name = "Azerbaijan")]
            //AZ = 994,
            //[Display(Name = "Bahamas")]
            //BS = 242,
            //[Display(Name = "Bahrain")]
            //BH = 973,
            //[Display(Name = "Bangladesh")]
            //BD = 880,
            //[Display(Name = "Barbados")]
            //BB = 246,
            //[Display(Name = "Belarus")]
            //BY = 375,
            //[Display(Name = "Belgium")]
            //BE = 32,
            //[Display(Name = "Belize")]
            //BZ = 501,
            //[Display(Name = "Benin")]
            //BJ = 229,
            //[Display(Name = "Bermuda")]
            //Bermuda = 441,
            //[Display(Name = "Bhutan")]
            //BM = 975,
            //[Display(Name = "Bolivia")]
            //BO = 591,
            //[Display(Name = "Bosnia and Herzegovina")]
            //BA = 387,
            //[Display(Name = "Botswana")]
            //BW = 267,
            //[Display(Name = "Bouvet Island")]
            //BV = 47,
            //[Display(Name = "Brazil")]
            //BR = 55,
            //[Display(Name = "British Indian Ocean Territory")]
            //IO = 246,
            //[Display(Name = "Brunei Darussalam")]
            //BN = 673,
            //[Display(Name = "Bulgaria")]
            //BG = 359,
            //[Display(Name = "Burkina Faso")]
            //BF = 226,
            //[Display(Name = "Burundi")]
            //Burundi = 257,
            //[Display(Name = "Cambodia")]
            //BI = 855,
            //[Display(Name = "Cameroon")]
            //CM = 237,
            //[Display(Name = "Canada")]
            //CA = 1,
            //[Display(Name = "Cape Verde")]
            //CV = 238,
            //[Display(Name = "Cayman Islands")]
            //KY = 345,
            //[Display(Name = "Central African Republic")]
            //CF = 236,
            //[Display(Name = "Chad")]
            //TD = 235,
            //[Display(Name = "Chile")]
            //CL = 56,
            //[Display(Name = "China")]
            //CN = 86,
            //[Display(Name = "Christmas Island")]
            //CX = 61,
            //[Display(Name = "Cocos (Keeling) Islands")]
            //CC = 61,
            //[Display(Name = "Colombia")]
            //CO = 57,
            //[Display(Name = "Comoros")]
            //KM = 269,
            //[Display(Name = "Congo (Brazzaville)")]
            //CG = 242,
            //[Display(Name = "Congo (Kinshasa)")]
            //CD = 243,
            //[Display(Name = "Cook Islands")]
            //CK = 682,
            //[Display(Name = "Costa Rica")]
            //CR = 506,
            //[Display(Name = "Côte d'Ivoire")]
            //CI = 225,
            //[Display(Name = "Croatia")]
            //HR = 385,
            //[Display(Name = "Cuba")]
            //CU = 53,
            //[Display(Name = "Cyprus")]
            //CY = 357,
            //[Display(Name = "Czech Republic")]
            //CZ = 420,
            //[Display(Name = "Denmark")]
            //DK = 45,
            //[Display(Name = "Djibouti")]
            //DJ = 253,
            //[Display(Name = "Dominica")]
            //DM = 767,
            //[Display(Name = "Dominican Republic")]
            //DO = 809,
            //[Display(Name = "Ecuador")]
            //EC = 593,
            //[Display(Name = "Egypt")]
            //EG = 20,
            //[Display(Name = "El Salvador")]
            //SV = 503,
            //[Display(Name = "Equatorial Guinea")]
            //GQ = 240,
            //[Display(Name = "Eritrea")]
            //ER = 291,
            //[Display(Name = "Estonia")]
            //EE = 372,
            //[Display(Name = "Ethiopia")]
            //ET = 251,
            //[Display(Name = "Falkland Islands")]
            //FK = 500,
            //[Display(Name = "Faroe Islands")]
            //FO = 298,
            //[Display(Name = "Fiji")]
            //FJ = 679,
            //[Display(Name = "Finland")]
            //FI = 358,
            //[Display(Name = "France")]
            //FR = 33,
            //[Display(Name = "French Guiana")]
            //GF = 594,
            //[Display(Name = "French Polynesia")]
            //PF = 689,
            //[Display(Name = "French Southern Lands")]
            //TF = 262,
            //[Display(Name = "Gabon")]
            //GA = 241,
            //[Display(Name = "Gambia")]
            //GM = 220,
            //[Display(Name = "Georgia")]
            //GE = 995,
            //[Display(Name = "Germany")]
            //DE = 49,
            //[Display(Name = "Ghana")]
            //GH = 233,
            //[Display(Name = "Gibraltar")]
            //GI = 350,
            //[Display(Name = "Greece")]
            //GR = 30,
            //[Display(Name = "Greenland")]
            //GL = 299,
            //[Display(Name = "Grenada")]
            //GD = 473,
            //[Display(Name = "Guadeloupe")]
            //GP = 590,
            //[Display(Name = "Guam")]
            //GU = 671,
            //[Display(Name = "Guatemala")]
            //GT = 502,
            //[Display(Name = "Guinea")]
            //GN = 224,
            //[Display(Name = "Guinea-Bissau")]
            //GW = 245,
            //[Display(Name = "Guyana")]
            //GY = 592,
            //[Display(Name = "Haiti")]
            //HT = 509,
            //[Display(Name = "Heard and McDonald Islands")]
            //HM = 61,
            //[Display(Name = "Honduras")]
            //HN = 504,
            //[Display(Name = "Hungary")]
            //HU = 36,
            //[Display(Name = "Iceland")]
            //IS = 354,
            //[Display(Name = "India")]
            //IN = 91,
            //[Display(Name = "Indonesia")]
            //ID = 62,
            //[Display(Name = "Iran")]
            //IR = 98,
            //[Display(Name = "Iraq")]
            //IQ = 964,
            //[Display(Name = "Ireland")]
            //IE = 353,
            //[Display(Name = "Israel")]
            //Israel = 972,
            //[Display(Name = "Italy")]
            //IL = 39,
            //[Display(Name = "Jamaica")]
            //JM = 876,
            //[Display(Name = "Japan")]
            //JP = 81,
            //[Display(Name = "Jordan")]
            //JO = 962,
            //[Display(Name = "Kazakhstan")]
            //KZ = 7,
            //[Display(Name = "Kenya")]
            //KE = 254,
            //[Display(Name = "Kiribati")]
            //KI = 686,
            //[Display(Name = "Kuwait")]
            //KW = 965,
            //[Display(Name = "Kyrgyzstan")]
            //KG = 996,
            //[Display(Name = "Laos LA")]
            //LA = 856,
            //[Display(Name = "Latvia")]
            //LV = 371,
            //[Display(Name = "Lebanon")]
            //LB = 961,
            //[Display(Name = "Lesotho")]
            //LS = 266,
            //[Display(Name = "Liberia")]
            //LR = 231,
            //[Display(Name = "Libya")]
            //LY = 218,
            //[Display(Name = "Liechtenstein")]
            //LI = 423,
            //[Display(Name = "Lithuania")]
            //LT = 370,
            //[Display(Name = "Luxembourg")]
            //LU = 352,
            //[Display(Name = "Macedonia")]
            //MK = 389,
            //[Display(Name = "Madagascar")]
            //MG = 261,
            //[Display(Name = "Malawi")]
            //MW = 265,
            //[Display(Name = "Malaysia")]
            //MY = 60,
            //[Display(Name = "Maldives")]
            //MV = 960,
            //[Display(Name = "Mali")]
            //ML = 223,
            //[Display(Name = "Malta")]
            //MT = 356,
            //[Display(Name = "Marshall Islands")]
            //MH = 692,
            //[Display(Name = "Martinique")]
            //MQ = 596,
            //[Display(Name = "Mauritania")]
            //MR = 222,
            //[Display(Name = "Mauritius")]
            //MU = 230,
            //[Display(Name = "Mayotte")]
            //YT = 262,
            //[Display(Name = "Mexico")]
            //MX = 52,
            //[Display(Name = "Micronesia")]
            //FM = 691,
            //[Display(Name = "Moldova")]
            //MD = 373,
            //[Display(Name = "Monaco")]
            //MC = 377,
            //[Display(Name = "Mongolia")]
            //MN = 976,
            //[Display(Name = "Montenegro")]
            //ME = 382,
            //[Display(Name = "Montserrat")]
            //MS = 664,
            //[Display(Name = "Morocco")]
            //MA = 212,
            //[Display(Name = "Mozambique")]
            //MZ = 258,
            //[Display(Name = "Myanmar")]
            //MM = 95,
            //[Display(Name = "Namibia")]
            //NA = 264,
            //[Display(Name = "Nauru")]
            //NR = 674,
            //[Display(Name = "Nepal")]
            //NP = 977,
            //[Display(Name = "Netherlands Antilles")]
            //NAL = 599,
            //[Display(Name = "Netherlands")]
            //NL = 31,
            //[Display(Name = "New Caledonia")]
            //NC = 687,
            //[Display(Name = "New Zealand")]
            //NZ = 64,
            //[Display(Name = "Nicaragua")]
            //NI = 505,
            //[Display(Name = "Niger")]
            //NE = 227,
            //[Display(Name = "Nigeria")]
            //NG = 234,
            //[Display(Name = "Niue")]
            //NU = 683,
            //[Display(Name = "Norfolk Island")]
            //NF = 672,
            //[Display(Name = "North Korea")]
            //KP = 850,
            //[Display(Name = "Northern Mariana Islands")]
            //MP = 670,
            //[Display(Name = "Norway")]
            //NO = 47,
            //[Display(Name = "Oman")]
            //OM = 968,
            //[Display(Name = "Pakistan")]
            //PK = 92,
            //[Display(Name = "Palau")]
            //PW = 680,
            //[Display(Name = "Palestine")]
            //PS = 970,
            //[Display(Name = "Panama")]
            //PA = 507,
            //[Display(Name = "Papua New Guinea")]
            //PG = 675,
            //[Display(Name = "Paraguay")]
            //PY = 595,
            //[Display(Name = "Peru")]
            //PE = 51,
            [Display(Name = "Philippines")]
            PH = 63,
            //[Display(Name = "Pitcairn Islands")]
            //PN = 64,
            //[Display(Name = "Poland")]
            //PL = 48,
            //[Display(Name = "Portugal")]
            //PT = 351,
            //[Display(Name = "Puerto Rico")]
            //PR2 = 939,
            //[Display(Name = "Qatar")]
            //QA = 974,
            //[Display(Name = "Reunion")]
            //RE = 262,
            //[Display(Name = "Romania")]
            //RO = 40,
            //[Display(Name = "Russian Federation")]
            //RU = 7,
            //[Display(Name = "Rwanda")]
            //RW = 250,
            //[Display(Name = "Saint Helena")]
            //SH = 290,
            //[Display(Name = "Saint Kitts and Nevis")]
            //KN = 869,
            //[Display(Name = "Saint Lucia")]
            //LC = 758,
            //[Display(Name = "Saint Pierre and Miquelon")]
            //PM = 508,
            //[Display(Name = "Saint Vincent and the Grenadines")]
            //VC = 784,
            //[Display(Name = "Samoa")]
            //WS = 685,
            //[Display(Name = "San Marino")]
            //SM = 378,
            //[Display(Name = "Sao Tome and Principe")]
            //ST = 239,
            //[Display(Name = "Saudi Arabia")]
            //SA = 966,
            //[Display(Name = "Senegal")]
            //SN = 221,
            //[Display(Name = "Serbia")]
            //RS = 381,
            //[Display(Name = "Seychelles")]
            //SC = 248,
            //[Display(Name = "Sierra Leone")]
            //SL = 232,
            //[Display(Name = "Singapore")]
            //SG = 65,
            //[Display(Name = "Slovakia")]
            //SK = 421,
            //[Display(Name = "Slovenia")]
            //SI = 386,
            //[Display(Name = "Solomon Islands")]
            //SB = 677,
            //[Display(Name = "Somalia")]
            //SO = 252,
            //[Display(Name = "South Africa")]
            //ZA = 27,
            //[Display(Name = "South Georgia and South Sandwich Islands")]
            //GS = 500,
            //[Display(Name = "South Korea")]
            //KR = 82,
            //[Display(Name = "Spain")]
            //ES = 34,
            //[Display(Name = "Sri Lanka")]
            //LK = 94,
            //[Display(Name = "Sudan")]
            //SD = 249,
            //[Display(Name = "Suriname")]
            //SR = 597,
            //[Display(Name = "Svalbard and Jan Mayen Islands")]
            //SJ = 47,
            //[Display(Name = "Swaziland")]
            //SZ = 268,
            //[Display(Name = "Sweden")]
            //SE = 46,
            //[Display(Name = "Switzerland")]
            //CH = 41,
            //[Display(Name = "Syria")]
            //SY = 963,
            //[Display(Name = "Taiwan")]
            //TW = 886,
            //[Display(Name = "Tajikistan")]
            //TJ = 992,
            //[Display(Name = "Tanzania")]
            //TZ = 255,
            //[Display(Name = "Thailand")]
            //TH = 66,
            //[Display(Name = "Timor-Leste")]
            //TL = 670,
            //[Display(Name = "Togo")]
            //TG = 228,
            //[Display(Name = "Tokelau")]
            //TK = 690,
            //[Display(Name = "Tonga")]
            //TO = 676,
            //[Display(Name = "Trinidad and Tobago")]
            //TT = 868,
            //[Display(Name = "Tunisia")]
            //TN = 216,
            //[Display(Name = "Turkey")]
            //TR = 90,
            //[Display(Name = "Turkmenistan")]
            //TM = 993,
            //[Display(Name = "Turks and Caicos Islands")]
            //TC = 649,
            //[Display(Name = "Tuvalu")]
            //TV = 688,
            //[Display(Name = "Uganda")]
            //UG = 256,
            //[Display(Name = "Ukraine")]
            //UA = 380,
            //[Display(Name = "United Arab Emirates")]
            //AE = 971,
            //[Display(Name = "United Kingdom")]
            //UK = 44,
            //[Display(Name = "Uruguay")]
            //UY = 598,
            //[Display(Name = "US Minor Outlying Islands")]
            //UM = 699,
            //[Display(Name = "USA")]
            //US = 1,
            //[Display(Name = "Uzbekistan")]
            //UZ = 998,
            //[Display(Name = "Vanuatu")]
            //VU = 678,
            //[Display(Name = "Vatican City")]
            //VA = 379,
            //[Display(Name = "Venezuela")]
            //VE = 58,
            //[Display(Name = "Vietnam")]
            //VN = 84,
            //[Display(Name = "Virgin Islands (British)")]
            //VG = 284,
            //[Display(Name = "Virgin Islands (U.S.)")]
            //VI = 340,
            //[Display(Name = "Wallis and Futuna Islands")]
            //WF = 681,
            //[Display(Name = "Western Sahara")]
            //EH = 212,
            //[Display(Name = "Yemen")]
            //YE = 967,
            //[Display(Name = "Zambia")]
            //ZM = 260,
            //[Display(Name = "Zimbabwe")]
            //ZW = 263
        };
    }
}
